# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /data/data/com.termux/files/usr/bin/sh

# The CMake executable.
CMAKE_COMMAND = /data/data/com.termux/files/usr/bin/cmake

# The command to remove a file.
RM = /data/data/com.termux/files/usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /data/data/com.termux/files/home/tty_game

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /data/data/com.termux/files/home/tty_game

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/data/data/com.termux/files/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/data/data/com.termux/files/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /data/data/com.termux/files/home/tty_game/CMakeFiles /data/data/com.termux/files/home/tty_game//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /data/data/com.termux/files/home/tty_game/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tty_game

# Build rule for target.
tty_game: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tty_game
.PHONY : tty_game

# fast build rule for target.
tty_game/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tty_game.dir/build.make CMakeFiles/tty_game.dir/build
.PHONY : tty_game/fast

CMakeFiles/3.31.5/CompilerIdC/CMakeCCompilerId.o: CMakeFiles/3.31.5/CompilerIdC/CMakeCCompilerId.c.o
.PHONY : CMakeFiles/3.31.5/CompilerIdC/CMakeCCompilerId.o

# target to build an object file
CMakeFiles/3.31.5/CompilerIdC/CMakeCCompilerId.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tty_game.dir/build.make CMakeFiles/tty_game.dir/CMakeFiles/3.31.5/CompilerIdC/CMakeCCompilerId.c.o
.PHONY : CMakeFiles/3.31.5/CompilerIdC/CMakeCCompilerId.c.o

CMakeFiles/3.31.5/CompilerIdC/CMakeCCompilerId.i: CMakeFiles/3.31.5/CompilerIdC/CMakeCCompilerId.c.i
.PHONY : CMakeFiles/3.31.5/CompilerIdC/CMakeCCompilerId.i

# target to preprocess a source file
CMakeFiles/3.31.5/CompilerIdC/CMakeCCompilerId.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tty_game.dir/build.make CMakeFiles/tty_game.dir/CMakeFiles/3.31.5/CompilerIdC/CMakeCCompilerId.c.i
.PHONY : CMakeFiles/3.31.5/CompilerIdC/CMakeCCompilerId.c.i

CMakeFiles/3.31.5/CompilerIdC/CMakeCCompilerId.s: CMakeFiles/3.31.5/CompilerIdC/CMakeCCompilerId.c.s
.PHONY : CMakeFiles/3.31.5/CompilerIdC/CMakeCCompilerId.s

# target to generate assembly for a file
CMakeFiles/3.31.5/CompilerIdC/CMakeCCompilerId.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tty_game.dir/build.make CMakeFiles/tty_game.dir/CMakeFiles/3.31.5/CompilerIdC/CMakeCCompilerId.c.s
.PHONY : CMakeFiles/3.31.5/CompilerIdC/CMakeCCompilerId.c.s

game/map/gfxinfo/clr.o: game/map/gfxinfo/clr.c.o
.PHONY : game/map/gfxinfo/clr.o

# target to build an object file
game/map/gfxinfo/clr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tty_game.dir/build.make CMakeFiles/tty_game.dir/game/map/gfxinfo/clr.c.o
.PHONY : game/map/gfxinfo/clr.c.o

game/map/gfxinfo/clr.i: game/map/gfxinfo/clr.c.i
.PHONY : game/map/gfxinfo/clr.i

# target to preprocess a source file
game/map/gfxinfo/clr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tty_game.dir/build.make CMakeFiles/tty_game.dir/game/map/gfxinfo/clr.c.i
.PHONY : game/map/gfxinfo/clr.c.i

game/map/gfxinfo/clr.s: game/map/gfxinfo/clr.c.s
.PHONY : game/map/gfxinfo/clr.s

# target to generate assembly for a file
game/map/gfxinfo/clr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tty_game.dir/build.make CMakeFiles/tty_game.dir/game/map/gfxinfo/clr.c.s
.PHONY : game/map/gfxinfo/clr.c.s

game/map/gfxinfo/gfxb.o: game/map/gfxinfo/gfxb.c.o
.PHONY : game/map/gfxinfo/gfxb.o

# target to build an object file
game/map/gfxinfo/gfxb.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tty_game.dir/build.make CMakeFiles/tty_game.dir/game/map/gfxinfo/gfxb.c.o
.PHONY : game/map/gfxinfo/gfxb.c.o

game/map/gfxinfo/gfxb.i: game/map/gfxinfo/gfxb.c.i
.PHONY : game/map/gfxinfo/gfxb.i

# target to preprocess a source file
game/map/gfxinfo/gfxb.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tty_game.dir/build.make CMakeFiles/tty_game.dir/game/map/gfxinfo/gfxb.c.i
.PHONY : game/map/gfxinfo/gfxb.c.i

game/map/gfxinfo/gfxb.s: game/map/gfxinfo/gfxb.c.s
.PHONY : game/map/gfxinfo/gfxb.s

# target to generate assembly for a file
game/map/gfxinfo/gfxb.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tty_game.dir/build.make CMakeFiles/tty_game.dir/game/map/gfxinfo/gfxb.c.s
.PHONY : game/map/gfxinfo/gfxb.c.s

game/map/gfxinfo/icon.o: game/map/gfxinfo/icon.c.o
.PHONY : game/map/gfxinfo/icon.o

# target to build an object file
game/map/gfxinfo/icon.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tty_game.dir/build.make CMakeFiles/tty_game.dir/game/map/gfxinfo/icon.c.o
.PHONY : game/map/gfxinfo/icon.c.o

game/map/gfxinfo/icon.i: game/map/gfxinfo/icon.c.i
.PHONY : game/map/gfxinfo/icon.i

# target to preprocess a source file
game/map/gfxinfo/icon.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tty_game.dir/build.make CMakeFiles/tty_game.dir/game/map/gfxinfo/icon.c.i
.PHONY : game/map/gfxinfo/icon.c.i

game/map/gfxinfo/icon.s: game/map/gfxinfo/icon.c.s
.PHONY : game/map/gfxinfo/icon.s

# target to generate assembly for a file
game/map/gfxinfo/icon.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tty_game.dir/build.make CMakeFiles/tty_game.dir/game/map/gfxinfo/icon.c.s
.PHONY : game/map/gfxinfo/icon.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tty_game.dir/build.make CMakeFiles/tty_game.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tty_game.dir/build.make CMakeFiles/tty_game.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tty_game.dir/build.make CMakeFiles/tty_game.dir/main.c.s
.PHONY : main.c.s

tty/in.o: tty/in.c.o
.PHONY : tty/in.o

# target to build an object file
tty/in.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tty_game.dir/build.make CMakeFiles/tty_game.dir/tty/in.c.o
.PHONY : tty/in.c.o

tty/in.i: tty/in.c.i
.PHONY : tty/in.i

# target to preprocess a source file
tty/in.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tty_game.dir/build.make CMakeFiles/tty_game.dir/tty/in.c.i
.PHONY : tty/in.c.i

tty/in.s: tty/in.c.s
.PHONY : tty/in.s

# target to generate assembly for a file
tty/in.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tty_game.dir/build.make CMakeFiles/tty_game.dir/tty/in.c.s
.PHONY : tty/in.c.s

tty/out.o: tty/out.c.o
.PHONY : tty/out.o

# target to build an object file
tty/out.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tty_game.dir/build.make CMakeFiles/tty_game.dir/tty/out.c.o
.PHONY : tty/out.c.o

tty/out.i: tty/out.c.i
.PHONY : tty/out.i

# target to preprocess a source file
tty/out.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tty_game.dir/build.make CMakeFiles/tty_game.dir/tty/out.c.i
.PHONY : tty/out.c.i

tty/out.s: tty/out.c.s
.PHONY : tty/out.s

# target to generate assembly for a file
tty/out.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tty_game.dir/build.make CMakeFiles/tty_game.dir/tty/out.c.s
.PHONY : tty/out.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... tty_game"
	@echo "... CMakeFiles/3.31.5/CompilerIdC/CMakeCCompilerId.o"
	@echo "... CMakeFiles/3.31.5/CompilerIdC/CMakeCCompilerId.i"
	@echo "... CMakeFiles/3.31.5/CompilerIdC/CMakeCCompilerId.s"
	@echo "... game/map/gfxinfo/clr.o"
	@echo "... game/map/gfxinfo/clr.i"
	@echo "... game/map/gfxinfo/clr.s"
	@echo "... game/map/gfxinfo/gfxb.o"
	@echo "... game/map/gfxinfo/gfxb.i"
	@echo "... game/map/gfxinfo/gfxb.s"
	@echo "... game/map/gfxinfo/icon.o"
	@echo "... game/map/gfxinfo/icon.i"
	@echo "... game/map/gfxinfo/icon.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... tty/in.o"
	@echo "... tty/in.i"
	@echo "... tty/in.s"
	@echo "... tty/out.o"
	@echo "... tty/out.i"
	@echo "... tty/out.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

