.TH Display documentation


.SH FILES
color.c/h gridbox.c/h

.SH ------------------------------------------------------------------------------------------------------------------------

.SH color.c/h
A color is just a byte of info about the attributes, foreground, and background about the color will be applied on
screen. 

.SH unsigned char mkclr(enum color_attr attr, enum color_id fg, enum color_id bg);
Creates a valid color using the info provided as arguments.

.SH int isvalclr(unsigned char clr);
Checks if the given byte is a valid color.

.SH int fputclr(FILE *f, unsigned char clr);
Prints the color to the specified file.

.SH ------------------------------------------------------------------------------------------------------------------------

.SH gridbox.c/h
A gridbox is just a character with coloring info byte.

.SH int isvalgbox(struct gridbox gbox);
Checks if a gridbox is valid.

.SH int fputgbox(FILE *f, struct gridbox gbox);
Prints a colored icon in the file specified.

.SH ------------------------------------------------------------------------------------------------------------------------

.SH window.c/h
A window is a bunch of gridboxes arranged in a W * H square.

.SH int mkwnd(struct window *wnd, struct window *hint);
Makes a window out of the hint provided, here are valid hints:

.SH int isvalwnd(struct window *wnd);
Checks if wnd is valid.

.SH int fputwnd(FILE *f, struct window *wnd);
Prints a 'window' of characters to the file specified.

.SH RETURN VALUES
The values returned by the functions!

.SH ------------------------------------------------------------------------------------------------------------------------

mkclr() returns a valid color byte, else 0.
.P
isvalclr() returns non-zero if valid color, else 0.
.P
fputclr() returns the number of bytes printed, else EOF.

.SH ------------------------------------------------------------------------------------------------------------------------

isvalgbox() returns non-zero if valid gridbox, else 0.
.P
fputgbox() returns the number of bytes printed, else EOF.

.SH ------------------------------------------------------------------------------------------------------------------------

mkwnd() returns 0 on success, 1 on failure.
.P
isvalwnd() returns 1 if valid, 0 if not.
.P
fputwnd() returns number of bytes printed, else EOF.

.SH That's all folks!
Goodbye guys and goodday/goodnight!
