.TH "src/game/map/cntxt/obj Directory Reference" 3 "tty_game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/game/map/cntxt/obj Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBobj\&.c\fP"
.br
.ti -1c
.RI "file \fBobj\&.h\fP"
.br
.ti -1c
.RI "file \fBobj_attr\&.h\fP"
.br
.in -1c
