.TH "src/tty Directory Reference" 3 "tty_game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tty Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBio\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBclr\&.c\fP"
.br
.ti -1c
.RI "file \fBclr\&.h\fP"
.br
.ti -1c
.RI "file \fBgfxb\&.c\fP"
.br
.ti -1c
.RI "file \fBgfxb\&.h\fP"
.br
.ti -1c
.RI "file \fBicon\&.c\fP"
.br
.ti -1c
.RI "file \fBicon\&.h\fP"
.br
.in -1c
