.TH "src/tty/clr.h" 3 "tty_game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tty/clr.h
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBclr_id\fP { \fBCID_BLACK\fP = 0x00, \fBCID_RED\fP = 0x01, \fBCID_GREEN\fP = 0x02, \fBCID_YELLOW\fP = 0x03, \fBCID_BLUE\fP = 0x04, \fBCID_PURPLE\fP = 0x05, \fBCID_CYAN\fP = 0x06, \fBCID_WHITE\fP = 0x07 }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "char \fBmkclr\fP (char cid_fg, char cid_bg)"
.br
.ti -1c
.RI "char \fBputclr\fP (char clr)"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBclr_id\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BICID_BLACK \fP
.TP
\f(BICID_RED \fP
.TP
\f(BICID_GREEN \fP
.TP
\f(BICID_YELLOW \fP
.TP
\f(BICID_BLUE \fP
.TP
\f(BICID_PURPLE \fP
.TP
\f(BICID_CYAN \fP
.TP
\f(BICID_WHITE \fP
.SH "Function Documentation"
.PP 
.SS "char mkclr (char cid_fg, char cid_bg)\fR [extern]\fP"

.SS "char putclr (char clr)\fR [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for tty_game from the source code\&.
