.TH "src/tty/gfxb.h" 3 "tty_game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tty/gfxb.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGFXBID_MAX\fP   2"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "char \fBputgfxb\fP (char \fBicon_id\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define GFXBID_MAX   2"

.SH "Function Documentation"
.PP 
.SS "char putgfxb (char icon_id)\fR [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for tty_game from the source code\&.
