.TH "src/tty/icon.h" 3 "tty_game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tty/icon.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBICONID_MAX\fP   3"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBicon_id\fP { \fBICONID_INVAL\fP = 0x00, \fBICONID_NONE\fP = 0x01, \fBICONID_WALL\fP = 0x02 }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "char \fBputicon\fP (char id)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ICONID_MAX   3"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBicon_id\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIICONID_INVAL \fP
.TP
\f(BIICONID_NONE \fP
.TP
\f(BIICONID_WALL \fP
.SH "Function Documentation"
.PP 
.SS "char puticon (char id)\fR [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for tty_game from the source code\&.
