.TH "src/tty/icon.c" 3 "tty_game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tty/icon.c
.SH SYNOPSIS
.br
.PP
\fR#include '\&./icon\&.h'\fP
.br
\fR#include '\&./io/out\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char \fBputicon\fP (char id)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char puticon (char id)"

.SH "Author"
.PP 
Generated automatically by Doxygen for tty_game from the source code\&.
