.TH "src/tty/io/in.c" 3 "tty_game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tty/io/in.c
.SH SYNOPSIS
.br
.PP
\fR#include '\&./in\&.h'\fP
.br
\fR#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char \fBpollb\fP (void)"
.br
.ti -1c
.RI "char \fBpollnb\fP (char count)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char pollb (void )"

.SS "char pollnb (char count)"

.SH "Author"
.PP 
Generated automatically by Doxygen for tty_game from the source code\&.
