.TH "src/game/map/cntxt/obj/obj.h" 3 "tty_game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/game/map/cntxt/obj/obj.h
.SH SYNOPSIS
.br
.PP
\fR#include '\&./obj_attr\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBobj\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBOBJID_MAX\fP   2"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBobj_id\fP { \fBOBJID_NONE\fP = 0x00, \fBOBJID_WALL\fP = 0x01 }"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBobj\fP \fBobj_table\fP [\fBOBJID_MAX\fP]"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define OBJID_MAX   2"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBobj_id\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIOBJID_NONE \fP
.TP
\f(BIOBJID_WALL \fP
.SH "Variable Documentation"
.PP 
.SS "struct \fBobj\fP obj_table[\fBOBJID_MAX\fP]\fR [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for tty_game from the source code\&.
