.TH "obj_normal" 3 "tty_game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
obj_normal
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <obj_attr\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBhp\fP"
.br
.ti -1c
.RI "char \fBdmg\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char obj_normal::dmg"

.SS "char obj_normal::hp"


.SH "Author"
.PP 
Generated automatically by Doxygen for tty_game from the source code\&.
