.TH "src/game/map/cntxt/obj/obj_attr.h" 3 "tty_game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/game/map/cntxt/obj/obj_attr.h
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBobj_normal\fP"
.br
.ti -1c
.RI "struct \fBobj_special\fP"
.br
.ti -1c
.RI "union \fBobj_attr\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBobj_attr_id\fP { \fBOBJAID_NORMAL\fP = 0x00, \fBOBJAID_SPECIAL\fP = 0x01 }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBobj_attr_id\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIOBJAID_NORMAL \fP
.TP
\f(BIOBJAID_SPECIAL \fP
.SH "Author"
.PP 
Generated automatically by Doxygen for tty_game from the source code\&.
