.TH "obj_attr" 3 "tty_game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
obj_attr
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <obj_attr\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBobj_normal\fP \fBnormal\fP"
.br
.ti -1c
.RI "struct \fBobj_special\fP \fBspecial\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBobj_normal\fP obj_attr::normal"

.SS "struct \fBobj_special\fP obj_attr::special"


.SH "Author"
.PP 
Generated automatically by Doxygen for tty_game from the source code\&.
