.TH "src/tty/io/out.c" 3 "tty_game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tty/io/out.c
.SH SYNOPSIS
.br
.PP
\fR#include '\&./out\&.h'\fP
.br
\fR#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char \fBputb\fP (char byte)"
.br
.ti -1c
.RI "char \fBprintb\fP (char *str)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char printb (char * str)"

.SS "char putb (char byte)"

.SH "Author"
.PP 
Generated automatically by Doxygen for tty_game from the source code\&.
