.TH "src/tty/io/out.h" 3 "tty_game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tty/io/out.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBOUT_ERR\fP   0xff"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "char \fBputb\fP (char byte)"
.br
.ti -1c
.RI "char \fBprintb\fP (char *str)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define OUT_ERR   0xff"

.SH "Function Documentation"
.PP 
.SS "char printb (char * str)\fR [extern]\fP"

.SS "char putb (char byte)\fR [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for tty_game from the source code\&.
