.TH "src/game/map/sect.h" 3 "tty_game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/game/map/sect.h
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBsector\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSECTORWIDTH\fP   40"
.br
.ti -1c
.RI "#define \fBSECTORHEIGHT\fP   20"
.br
.ti -1c
.RI "#define \fBSECTORSIZE\fP   (\fBSECTORWIDTH\fP * \fBSECTORHEIGHT\fP)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "char \fBputsector\fP (struct \fBsector\fP *\fBsector\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SECTORHEIGHT   20"

.SS "#define SECTORSIZE   (\fBSECTORWIDTH\fP * \fBSECTORHEIGHT\fP)"

.SS "#define SECTORWIDTH   40"

.SH "Function Documentation"
.PP 
.SS "char putsector (struct \fBsector\fP * sector)\fR [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for tty_game from the source code\&.
